name: Deploy
on:
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Run Web App
    runs-on: ubuntu-latest
    steps:
      - name: Build Web App
        run: |
          echo "Build Web App1"
      - uses: convictional/trigger-workflow-and-wait@v1.3.0
        with:
          owner: xHNxMrThanh
          repo: demo-web-api
          github_token: ${{ secrets.APP_TOKEN }}
          workflow_file_name: deploy.yml
          ref: master
          inputs: '{"name": "${{ github.ref }}","commitId": "${{ github.event.pull_request.head.sha }}"}'
      - name: Create comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: 1
          body: |
            This is a multi-line test comment
            - With GitHub **Markdown** :sparkles:
            - Created by [create-or-update-comment][1]
            [1]: https://github.com/peter-evans/create-or-update-comment
          reactions: '+1'