name: Deploy
on:
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Run Web App
    runs-on: ubuntu-latest
    steps:
      - name: Build Web App
        run: |
          echo "Build Web App1"
      - uses: convictional/trigger-workflow-and-wait@v1.3.0
        with:
          owner: xHNxMrThanh
          repo: demo-web-api
          github_token: ${{ secrets.APP_TOKEN }}
          workflow_file_name: deploy.yml
          ref: master
          inputs: '{"name": "${{ github.ref }}","commitId": "${{ github.event.pull_request.head.sha }}"}'
      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
      # Required mail server address:
          server_address: smtp.gmail.com
      # Required mail server port:
          server_port: 465
      # Optional (recommended): mail server username:
          username: ${{ secrets.EMAIL_ACCOUNT }}
      # Optional (recommended) mail server password:
          password: ${{ secrets.EMAIL_PASSWORD }}
      # Required mail subject:
          subject: Github Actions job result
      # Required recipients' addresses:
          to: thanh.phanduy@nttdata.com
      # Required sender full name (address can be skipped):
          from: Thanh Phan
          secure: true