name: Deploy
on:
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Run Web App
    runs-on: ubuntu-latest
    steps:
      - name: Build Web App
        run: |
          echo "Build Web App"
          sleep 10s
      - uses: convictional/trigger-workflow-and-wait@v1.3.0
        with:
          owner: xHNxMrThanh
          repo: demo-web-api
          github_token: ${{ secrets.APP_TOKEN }}
          workflow_file_name: deploy.yml
          ref: master
          inputs: '{"name":${{ github.base_ref }},"github.sha":${{ github.sha }},"github.head_ref":${{ github.head_ref }}}'
      - name: Deploy Web App
        run: |
          echo "Deploy Web App"
          sleep 10s